# Generated by Django 3.0b1 on 2019-12-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_auto_20191201_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
