# Generated by Django 3.0b1 on 2019-12-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_auto_20191201_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
