# Generated by Django 3.0b1 on 2019-12-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_auto_20191203_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='email',
            field=models.EmailField(default='KRCL@krcl.org', max_length=320),
        ),
        migrations.AddField(
            model_name='timeline',
            name='name',
            field=models.CharField(default='KRCL', max_length=128),
        ),
    ]
