# Generated by Django 3.0b1 on 2019-12-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_auto_20191203_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='story',
            field=models.TextField(max_length=512),
        ),
    ]
