# Generated by Django 3.0b1 on 2019-12-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0011_auto_20191203_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='fileUp',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
