# Generated by Django 3.0b1 on 2019-12-10 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0012_timeline_fileup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='fileUp',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'gif', 'png', 'jpeg', 'mp4', 'mp3', 'm4a', 'wav'])]),
        ),
    ]
