# Generated by Django 3.0b1 on 2019-12-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0013_auto_20191209_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='fileUp',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
